### PR TITLE
Theme transient

### PR DESCRIPTION
**Pull request by manuel-uberti**
This is a first attempt at adding support for [transient](https://emacsair.me/2019/02/14/transient-0.1/).

Have a look at the new colours in Magit before merging this, please. If colours are not what you are expecting, I'm happy to change them in order to keep the theme consistent.

### CODE REVIEW

**Comment by drot** [comment]
I'm not sure if we would want to override all of the faces because almost all of them inherit from various `font-lock-*` faces. The only ones that don't are `transient-enabled-suffix` and `transient-disabled-suffix` so those would be OK changes. @purcell thoughts?

**Comment by manuel-uberti** [comment]
Thank you.

I changed `alt-background` to `low-contrast-bg` for now. Let's see what @purcell thinks and then I'll change the PR accordingly.

**Comment by purcell** [comment]
> I'm not sure if we would want to override all of the faces because almost all of them inherit from various `font-lock-*` faces.

I kinda agree: I guess the desired outcome is for the transient buffers to look like the magit-popup buffers. Do the default inherited face definitions accomplish that when this theme is enabled? If not, then I guess the faces _do_ need to be styled here.

**Comment by manuel-uberti** [comment]
Yes, with only the two faces mentioned by @drot the result is what we are looking for I guess. Just press <kbd>b</kbd> and then <kbd>C-x l</kbd> to see the two themed faces if you want to check the result with this PR.

Thanks again guys.

**Comment by manuel-uberti** [comment]
This is what it looks like now:

screenshot

**Comment by purcell** [comment]
Great, thanks - merged!

**Pull request merged**
