### PR TITLE
Extend Magit faces

### PR DESCRIPTION
**Pull request by manuel-uberti**
I applied `:extend t` to the faces that look related to diff/section/hunk highlighting.

See: https://github.com/purcell/color-theme-sanityinc-tomorrow/issues/140

### CODE REVIEW

**Comment by purcell** [comment]
Super, thanks

**Comment by manuel-uberti** [comment]
Still, if Magit is loaded after the theme these changes will be overridden, won't they?

**Comment by purcell** [comment]
I think Magit would only redundantly set that property, so it shouldn't be a problem: the rest of the face definition specified here should remain as we wish. Let me know if that's not how it works in practice!

**Comment by manuel-uberti** [comment]
The problem is I don't see `:extend t` applied correctly. The rest of the faces are correctly applied, meaning Magit is themed accordingly to what is defined here. But the faces are still not *extended*, even though I see this PR correctly applied.

**Comment by purcell** [comment]
I'm not sure what to do, then, sorry. Do you have an opinion? I'm not using Emacs 27 and don't really want to get into debugging this.

**Comment by manuel-uberti** [comment]
Don't worry, it's obviously not the theme's fault at this point. Let's leave the theme as it is, because it's definitely taking care of the faces that are supposed to be extend.

I'll keep monitoring the situation on Emacs `master` and see if anything needs to be updated on the theme. :)

**Pull request merged**
