### PR TITLE
add faces specific to cperl-mode

### PR DESCRIPTION
**Pull request by nega0**
- add faces specific to `cperl-mode`
- comments include `cperl-mode`'s defaults

### CODE REVIEW

**Comment by drot** [comment]
`custom-theme-set-faces` is already being called by the macro and we don't really need the comment about the defaults. Would you agree on something like this?

```
;; cperl-mode (built-in)
(cperl-array-face (:foreground ,yellow :background ,blue :weight bold))
(cperl-hash-face (:foreground ,red :background ,contrast-bg :weight bold))
(cperl-nonoverridable-face (:foreground ,purple))
```

**Comment by nega0** [comment]
> `custom-theme-set-faces` is already being called by the macro and we don't really need the comment about the defaults. Would you agree on something like this?
> 
I know. I specifically did it that way to get different colors for `*-day` with its light background.

**Comment by purcell** [comment]
> > 
> 
> I know. I specifically did it that way to get different colors for `*-day` with its light background.

That really shouldn't be necessary, and that's not how this theme is designed to work. I can't see any reason why cperl would be unique in this regard.

**Comment by nega0** [comment]
> That really shouldn't be necessary, 

It's necessary for me.

> and that's not how this theme is designed to work.

I didn't read that anywhere Kempson's or your design docs / contribution guidelines. :wink:

> I can't see any reason why cperl would be unique in this regard.

It doesn't have to be for this theme, but it's `cperl-mode`'s default behavior.

`cperl-mode` [defines light and dark faces](https://github.com/emacs-mirror/emacs/blob/9e0d69b5a17a0fa3b0dd099a51584a85f3ddb5bf/lisp/progmodes/cperl-mode.el#L632-L674) for both grayscale and color displays. I like this behavior, and I've been using `cperl-mode` since long before it was integrated into Emacs. I also like the Tomorrow themes. **A lot.** I've integrated them in to everything I can under macOS and Linux, though I'm primarily Mac oriented these days.

`cperl-mode`'s defaults look like butt under Tomorrow themes.

cperl default, bright:
screen shot 2019-02-08 at 10 01 51 am

cperl default, day:
screen shot 2019-02-08 at 10 02 37 am

Attempting to find a good compromise between `cperl-mode`'s __behavior__, and Tomorrow's __colors__, I spent a good deal more time messing around with the colors, than implementing them. We're going from [seven-hundred something (named) colors](https://github.com/emacs-mirror/emacs/blob/9e0d69b5a17a0fa3b0dd099a51584a85f3ddb5bf/etc/rgb.txt#L788) to sixteen. Red on blue, still looked like butt. Yellow on blue, still looked like butt. Yellow on (low-)contrast-bg, looked like butt. So, I came up with the proposed patch that:

1. maintains expected/learned behavior
2. has a compromise of colors that are pleasant and close to the originals
3. doesn't break your brain when looking at strange Perl code
4. is minimally invasive
5. and descriptive (including the fourth `cperl-mode` specific face

my cperl, bright:
screen shot 2019-02-08 at 9 54 38 am

my cperl, day:
screen shot 2019-02-08 at 9 55 28 am

@drot's [proposed patch](https://github.com/purcell/color-theme-sanityinc-tomorrow/pull/123#issuecomment-461518484) has half of `#2`, and and `#4`. 

proposed cperl, bright:
screen shot 2019-02-08 at 9 58 01 am

proposed cperl, day:
screen shot 2019-02-08 at 9 58 54 am

Anyway, there's my push. I've got a patch that I think looks nice and doesn't break my workflow (code flow? reading flow? code reading flow?) and I want you and anyone else to have it. At the end of they day, I know you can just "close/wontaccept" and that'll suck. I'll have to stop `(use-package`'ing, and find some clever way to maintain a fork and my init files. But, I'll hope you'll take the time to read the whole comment, look at the screen shots, and take some time to consider my points. And then click 'merge' :wink:

**Comment by purcell** [comment]
> I didn't read that anywhere Kempson's or your design docs / contribution guidelines.

Thanks for the screenshots and laying out your thought process.

While not written down, I think there are two fairly clear principles of these themes that this patch doesn't follow:

1. Foreground colours aren't meant to be combined with other foreground colours to form `:foreground`/`:background` pairs.
2. Faces shouldn't change colour between the various Tomorrow themes, ie. if a face is green in one theme, it should be green in the others.

>     1. maintains expected/learned behavior

This is not a goal of "normalised" themes like this: we've paid no attention to builtin defaults when choosing all the other faces. It's more important that the faces look consistent with their neighbours and are reasonably distinct in their typical contexts.

Nonetheless I've separately made changes in e6740a9 to add definitions for the three cperl faces that take some pointers from the defaults. I prefer to go with this simpler solution, since it follows the two principles above, and I'm happy to hear feedback. Thanks for prodding us to add these faces.

**Comment by nega0** [comment]
> Nonetheless I've separately made changes in e6740a9 to add definitions for the three cperl faces that take some pointers from the defaults. I prefer to go with this simpler solution, since it follows the two principles above, and I'm happy to hear feedback. Thanks for prodding us to add these faces.

All perfectly reasonable. Thanks for adding the faces.

**Pull request closed without merging**
