### PR TITLE
Theme helm-ls-git

### PR DESCRIPTION
**Pull request by manuel-uberti**
This PR adds support for [helm-ls-git](https://github.com/emacs-helm/helm-ls-git).

### CODE REVIEW

**Comment by manuel-uberti** [comment]
@purcell friendly ping, but only because I have another PR ready to submit and I don't want to flood you with my requests. :)

**Comment by purcell** [comment]
Thanks!

**Comment by manuel-uberti** [comment]
Thank you, Steve. Also, sorry about the mess up, my other changes for CIDER faces sneaked into this PR, which reminds I should *not* code on Sundays.

**Comment by purcell** [comment]
No worries, those changes looked okay to me too, so I just rolled them in. :-)

**Pull request merged**
